from enum import Enum


class MatchmakingFieldGroup(str, Enum):
    SKILL = "skill"
    TARGET_GROUP = "target_group"
    LANGUAGE_SPOKEN = "language_spoken"
    VOLUNTEERING_FREQUENCY = "volunteering_frequency"

class VolunteeringFrequency(str, Enum):
    SUNDAY = "Sunday"
    MONDAY = "Monday"
    TUESDAY = "Tuesday"
    WEDNESDAY = "Wednesday"
    THURSDAY = "Thursday"
    FRIDAY = "Friday"
    SATURDAY = "Saturday"

class TargetGroup(str, Enum):
    ADULTS = "Adults"
    ANIMAL_WELFARE = "Animal welfare"
    ANIMALS = "Animals"
    ARTS_CULTURE_HERITAGE = "Arts, culture and heritage"
    CAREGIVERS = "Caregivers"
    CHILDREN = "Children"
    COMMUNITY_DEVELOPMENT = "Community development"
    DISASTER_CRISIS_VICTIMS = "Disaster/Crisis victims"
    EDUCATION = "Education"
    ELDERLY = "Elderly"
    ENVIRONMENTAL_PROTECTION_SUSTAINABILITY = "Environmental protection and sustainability"
    ETHNIC_GROUPS = "Ethnic groups"
    FAMILIES = "Families"
    FOREIGN_WORKERS = "Foreign workers"
    GENDER_GROUPS = "Gender groups"
    GENERAL_POPULATION = "General population"
    HEALTHCARE = "Healthcare"
    INCARCERATED_INDIVIDUALS = "Incarcerated individuals"
    LOCAL_COMMUNITY = "Local community"
    LOW_INCOME_GROUPS = "Low-income groups"
    OTHER_OVERSEAS_CAUSES = "Other overseas causes"
    OVERSEAS_HUMANITARIAN_AID = "Overseas humanitarian aid"
    PERSONS_LIVING_WITH_DEMENTIA = "Persons living with dementia"
    PERSONS_LIVING_WITH_MEDICAL_ILLNESSES = "Persons living with medical illnesses"
    PERSONS_WITH_DISABILITIES = "Persons with disabilities"
    PERSONS_WITH_MENTAL_HEALTH_CONDITIONS = "Persons with mental health conditions"
    SOCIAL_SERVICE_WELFARE = "Social service and welfare"
    SPORTS = "Sports"
    THE_ENVIRONMENT = "The environment"
    YOUTH = "Youth"

class Skills(str, Enum):
    ACCOUNTING_FINANCE = "Accounting and finance"
    ARTS_MUSIC = "Arts and music"
    BUSINESS_DEVELOPMENT = "Business development"
    COACHING_TRAINING = "Coaching and training"
    COUNSELLING_MENTORING = "Counselling and mentoring"
    FUNDRAISING = "Fundraising"
    HUMAN_RESOURCE = "Human resource"
    INFORMATION_TECHNOLOGY = "Information technology"
    LEADER_DEVELOPMENT = "Leader development"
    LEGAL = "Legal"
    MARKETING_COMMUNICATIONS = "Marketing and communications"
    MEDICAL_HEALTH = "Medical and health"
    VOLUNTEER_MANAGEMENT = "Volunteer management"
    EVENT_MANAGEMENT = "Event management"
