"""add ddc description field

Revision ID: 00163d17eb9f
Revises: 5e6c5e7e725b
Create Date: 2024-11-30 04:30:14.550857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00163d17eb9f'
down_revision: Union[str, None] = '5e6c5e7e725b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dementia_daycare', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dementia_daycare', 'description')
    # ### end Alembic commands ###
