"""add pchi info

Revision ID: 5e6c5e7e725b
Revises: 000c3a1f81b6
Create Date: 2024-11-29 11:49:48.460767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5e6c5e7e725b'
down_revision: Union[str, None] = '000c3a1f81b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('household_size', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_monthly_household_income', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('annual_property_value', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('monthly_pchi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_pchi')
    op.drop_column('users', 'annual_property_value')
    op.drop_column('users', 'total_monthly_household_income')
    op.drop_column('users', 'household_size')
    # ### end Alembic commands ###
