"""add daycare price info

Revision ID: 000c3a1f81b6
Revises: f712f66f5d9f
Create Date: 2024-11-28 23:51:40.661598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000c3a1f81b6'
down_revision: Union[str, None] = 'f712f66f5d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dementia_daycare', sa.Column('min_price', sa.Integer(), nullable=True))
    op.add_column('dementia_daycare', sa.Column('max_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dementia_daycare', 'max_price')
    op.drop_column('dementia_daycare', 'min_price')
    # ### end Alembic commands ###
