"""remove authentication from admin

Revision ID: dc13cef70cea
Revises: c55594fb258d
Create Date: 2025-12-13 15:19:43.184319

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc13cef70cea"
down_revision: Union[str, Sequence[str], None] = "c55594fb258d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admin", sa.Column("clerk_id", sa.String(), nullable=True))
    op.execute("""UPDATE "admin" SET clerk_id = '' WHERE clerk_id IS NULL""")
    op.alter_column("admin", "clerk_id", nullable=False)

    op.add_column(
        "admin",
        sa.Column(
            "has_created_heartbeat_account",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column(
        "admin",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Primary key",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('admin_id_seq'::regclass)"),
    )
    op.alter_column(
        "admin",
        "username",
        existing_type=sa.VARCHAR(),
        nullable=True,
        comment=None,
        existing_comment="User's username; doubles as username",
    )
    op.alter_column(
        "admin",
        "contact_number",
        existing_type=postgresql.BYTEA(),
        nullable=True,
        existing_comment="Assumes SG phone number",
    )
    op.drop_column("admin", "name")
    op.drop_column("admin", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admin",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "admin",
        sa.Column("name", postgresql.BYTEA(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "admin",
        "contact_number",
        existing_type=postgresql.BYTEA(),
        nullable=False,
        existing_comment="Assumes SG phone number",
    )
    op.alter_column(
        "admin",
        "username",
        existing_type=sa.VARCHAR(),
        nullable=False,
        comment="User's username; doubles as username",
    )
    op.alter_column(
        "admin",
        "id",
        existing_type=sa.INTEGER(),
        comment="Primary key",
        existing_nullable=False,
        existing_server_default=sa.text("nextval('admin_id_seq'::regclass)"),
    )
    op.drop_column("admin", "has_created_heartbeat_account")
    op.drop_column("admin", "clerk_id")
    # ### end Alembic commands ###
