"""add block and unit to user table

Revision ID: 1839072e3a85
Revises: 97563b8dd47f
Create Date: 2025-12-11 12:16:58.629229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1839072e3a85"
down_revision: Union[str, Sequence[str], None] = "97563b8dd47f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("block", sa.String()))
    op.add_column("user", sa.Column("unit", sa.String()))

    op.execute("""UPDATE "user" SET block = '' WHERE block IS NULL""")
    op.execute("""UPDATE "user" SET unit = '' WHERE unit IS NULL""")

    op.alter_column("user", "block", nullable=False)
    op.alter_column("user", "unit", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "unit")
    op.drop_column("user", "block")
    # ### end Alembic commands ###
