"""remove has_created_heartbeat_account and username from admin table

Revision ID: dda2c516bc5a
Revises: dc13cef70cea
Create Date: 2025-12-17 08:59:28.762704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda2c516bc5a'
down_revision: Union[str, Sequence[str], None] = 'dc13cef70cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin', ['clerk_id'])
    op.drop_column('admin', 'has_created_heartbeat_account')
    op.drop_column('admin', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin', sa.Column('has_created_heartbeat_account', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin', type_='unique')
    # ### end Alembic commands ###
