"""add consecutive_non_checkins column to care_receipient table

Revision ID: ccccb0459f5b
Revises: 1f0eaf0d0ffe
Create Date: 2026-01-20 06:05:00.220188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccccb0459f5b'
down_revision: Union[str, Sequence[str], None] = '1f0eaf0d0ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_receipient', sa.Column('consecutive_non_checkins', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_receipient', 'consecutive_non_checkins')
    # ### end Alembic commands ###
