"""Integrate with heartbeat

Revision ID: 1f0eaf0d0ffe
Revises: 00163d17eb9f
Create Date: 2026-01-01 17:26:17.851817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy_utils import EncryptedType


# revision identifiers, used by Alembic.
revision: str = '1f0eaf0d0ffe'
down_revision: Union[str, None] = '00163d17eb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_receipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', EncryptedType(), nullable=False),
    sa.Column('contact_number', EncryptedType(), nullable=False, comment='Assumes SG phone number'),
    sa.Column('alias', sa.String(), nullable=False, comment='To prevent data overflow on frontend'),
    sa.Column('app_language', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('consecutive_checkins', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('can_record_mood', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('care_receipient_id', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Enum('HAPPY', 'OK', 'SAD', name='selectedmood'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['care_receipient_id'], ['care_receipient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('contact_number', EncryptedType(), nullable=True, comment='Assumes SG phone number'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    op.drop_table('mood')
    op.drop_table('care_receipient')
    op.execute('DROP TYPE selectedmood')
    # ### end Alembic commands ###
